#!/system/bin/sh

echo "=================================================="
echo "  OnePlus 13 HDR WebUI Management Tool"
echo "  Version 1.6.3 - Enhanced Edition"
echo "=================================================="
echo ""

echo "📱 For Magisk Users / Magisk 用户："
echo ""
echo "⚠️  IMPORTANT / 重要提醒："
echo "   Magisk Manager only shows 'Action' button, not 'WebUI'"
echo "   Magisk 管理器只显示\"操作\"按钮，没有 WebUI 按钮"
echo "   You need to use WebUI-X-Portable for WebUI access (RECOMMENDED)"
echo "   您需要使用 WebUI-X-Portable 来访问 WebUI（推荐）"
echo ""

echo "🎯 How to Access WebUI / 如何访问 WebUI："
echo ""
echo "🚀 RECOMMENDED - WebUI-X-Portable (Faster performance):"
echo "   📥 推荐下载 - WebUI-X-Portable（性能更快）："
echo "   https://github.com/MMRLApp/WebUI-X-Portable/releases"
echo "   💡 Supports both KernelSU and Magisk"
echo "      支持 KernelSU 和 Magisk"
echo ""
echo "📱 Alternative - KsuWebUI-Standalone:"
echo "   备选下载 - KsuWebUI-Standalone:"
echo "   https://github.com/5ec1cff/KsuWebUIStandalone/releases"
echo ""
echo "2️⃣  Install the APK file / 安装 APK 文件"
echo ""
echo "3️⃣  ⚠️  CRITICAL: Grant ROOT permissions to this app"
echo "   ⚠️  关键步骤：授予此应用 ROOT 权限"
echo "   (Required for reading/writing module files)"
echo "   （需要读写模块文件）"
echo ""
echo "4️⃣  Open the app and navigate to this module's WebUI"
echo "   打开应用并导航到此模块的 WebUI"
echo ""

echo "📱 Enhanced WebUI Features (v1.6.3) / 增强版 WebUI 功能 (v1.6.3)："
echo "   • ✨ Real-time app list saving (no manual save needed)"
echo "     实时应用列表保存（无需手动保存）"
echo "   • 🔍 Smart real-time search and filtering"
echo "     智能实时搜索和过滤"
echo "   • 💾 Persistent app name caching"
echo "     持久化应用名称缓存"
echo "   • 📦 Batch select/deselect operations"
echo "     批量选择/取消选择操作"
echo "   • ⚡ Optimized performance and loading"
echo "     优化性能和加载"
echo "   • 📱 Enhanced mobile-friendly interface"
echo "     增强移动端友好界面"
echo "   • 🛡️ Comprehensive error handling"
echo "     全面的错误处理机制"
echo ""

echo "=================================================="
echo ""
echo "⏰ 脚本将在60秒后自动退出..."
echo "   Script will auto-exit in 60 seconds..."
echo ""
echo "👋 感谢使用！Thanks for using!"
echo ""

# 60秒延时后自动退出
sleep 60

exit 0